### ISSUE TITLE
Need to add permanent link into the pages for the metrics models

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/wg-metrics-models#102]
Each CHAOSS metric has a line near the bottom that says:
* To reference this metric in software or publications please use this stable URL: https://chaoss.community/?p=####

We don't have this for the metrics model pages, but we should. You can look at the individual metrics pages to see how this should be formatted and where it should appear on the page. 

Here are the permanent links if someone wants to give this a go: [metric_model_links.csv](https://github.com/chaoss/wg-metrics-models/files/13515509/metric_model_links.csv)

This csv file has the web url, the GitHub URL of the file that needs to be updated, and the permanent URL that it should point to.

**Comment by nwanduka** [comment]
Hi @geekygirldawn, I've reviewed the issue description and the CVS file you shared and believe I can take on this task. Could you assign it to me, please?
