### ISSUE TITLE
Duplicate pages on the Safety metric model

### ISSUE THREAD

**Issue by nwanduka** [chaoss/wg-metrics-models#105]
**Current State:**

On the [Metric Model website](https://chaoss.community/kbtopic/all-metrics-models/), "Safety" is listed twice. It appears a second time as "Community Safety". Both pages contain the same information so one has to be removed - the "Community Safety" page.
<br/>
**Desired State:**
Remove the Community Safety page so that there's just one page for the Safety metric model.

//@geekygirldawn @ElizabethN

**Comment by ElizabethN** [comment]
@nwanduka thanks for this! I kept "Safety" and made "Community Safety" a draft, just in case. They were in fact duplicates as you said. Appreciate your help here, and apologies for the lonnnnnng delay in seeing this!
