### ISSUE TITLE
Create a page for the Community Welcomingness metric model

### ISSUE THREAD

**Issue by nwanduka** [chaoss/wg-metrics-models#106]
The "Community Welcomingness" metric model is in the [GitHub repo](https://github.com/chaoss/wg-metrics-models/blob/main/metrics-model-libs/community-welcomingness/definition/community-welcomingness.md) but not on the website. The desired state is to have a dedicated page for the Community Welcomingness metric model, like [the others listed](https://chaoss.community/kbtopic/all-metrics-models/) on the website.

// @geekygirldawn @ElizabethN

**Comment by ElizabethN** [comment]
[This is complete](https://chaoss.community/kb/metrics-model-community-welcomingness/)! Not sure what happened here, but thanks for catching this @nwanduka and @geekygirldawn
