### ISSUE TITLE
Metrics Model Design should include Difficulty or Time Investment associated audiences

### ISSUE THREAD

**Issue by emmairwin** [chaoss/wg-metrics-models#13]
In the model of a toolkit we should also indicate up front what the investment associated with a metric model.
For example if I have to setup a notebook, and query data then that's _medium_ to high investment, but if I just have to go to the GitHub dashboard, that's easy.

Similarly if I have to run a survey in an instance like phycological safety, we should indicate that is high investment, but also only available to certain audiences (the project maintainer, but not contributors or funders).    

I will demonstrate what this might look like in https://docs.google.com/document/d/1DpHhVMAwucaKoXoOYMCnmxZuhWMqWupDsZvWpxe_A0M/edit

**Comment by sgoggins** [comment]
@emmairwin : I think you are talking about "difficulty to develop", correct?

**Comment by germonprez** [comment]
@emmairwin -- thanks for the comments. We really worked through these but they created some difficulty in making that determination from our (CHAOSS) side of things.

**Comment by germonprez** [comment]
I'm closing this for now as we aren't including the difficulty right now. In an effort to simplify the definition of the metrics models, we are following the template at: https://github.com/chaoss/community/blob/main/templates/metrics-model-template.md
