### ISSUE TITLE
Web page for Bus factor metric (re)moved

### ISSUE THREAD

**Issue by camillem** [chaoss/wg-metrics-models#16]
Hi, 
Not sure this in the right place to report this, but the page https://chaoss.community/metric-bus-factor/ is now 404ing and couldn't find the new URL by searching the website.
Thanks, 
Camille

**Comment by germonprez** [comment]
Thanks for this @camillem. I think a better place for this issue is in https://github.com/chaoss/website. Do you want to close this issue and open it again over there?

**Comment by klumb** [comment]
I took a look at this. I can not recreate the problem. I will continue to monitor the site to see if I can observe the problem but I am closing this issue.

@camillem, If you are still experiencing the problem, please open an issue in the website repo.

Please include a screenshot with 404 and the URL. Also please let us know which browser you are using.

**Comment by camillem** [comment]
@germonprez thanks for the hint and sorry for the noise
@klumb : still experiencing the problem, will open an issue
