### ISSUE TITLE
The Problem with Metrics is a Fundamental Problem

### ISSUE THREAD

**Issue by bhack** [chaoss/wg-metrics-models#17]
It is partially connected to https://github.com/chaoss/wg-common/issues/164 and I think that it could also involve WG-risk.

This paper is a little bit oriented to AI but has still a nice general overview on what kind of mitigation we could adopt when we are going to rely on metrics as targets:

https://arxiv.org/abs/2002.08512

**Comment by bhack** [comment]
Just to add few other resources other then in the original ticket:
https://www.holistics.io/blog/four-types-goodharts-law/
https://mpra.ub.uni-muenchen.de/90649/1/MPRA_paper_90649.pdf

**Comment by bhack** [comment]
https://www.ribbonfarm.com/2016/06/09/goodharts-law-and-why-measurement-is-hard/

**Comment by bhack** [comment]
https://openai.com/blog/measuring-goodharts-law/

**Comment by bhack** [comment]
> How can we work together to bring some of your ideas forward as an actionable metrics model?

I'm not familiar with the way the group works as I'm pretty new.
I think that on one side we should try to involve some experts on this subject such as the author or related works. Is there any major conference on this issue?

In parallel, when we interact with the OSPOs, we should begin to understand how they direct resources, especially in "enterprise" opensource projects, since resources are often allocated to achieve objectives that for companies must be measurable. 
What do the OSPOs do? Do they transform our metrics into measurable goals? etc..

**Comment by bhack** [comment]
My proposal is to evaluate some section in the model template using 4.1/5.1 in https://mpra.ub.uni-muenchen.de/90649/1/MPRA_paper_90649.pdf:

1. Can we add for every single included metric a `Pre-gaming` analysts of the risk? 
2.  Coherence: what is the coherence of our metric model?

In the model (template) we could add a model card section where we define:


3. Diversification: how we have diversified our metrics portfolio to limit gaming?
> Because the different metrics typically
require different behaviors, and they will be to some extent in tension with one another,
they are likely to make gaming harder.
4. Randomization. What kind of randomization strategy we suggest? 
> the weights on compo-
nents or the relative rewards are uncertain, gaming the metric may become less worth-
while. 
5. What kind of soft-metrics we suggest to integrate when an Org is adopting a specific model?
> Human judgment, peer evaluation, and other techniques may be
able to reduce gaming specific to metrics. Metrics are often seen as a way to avoid
subjectivity, but a combination of metrics and human judgment may be able to capture
the best of both worlds.
6. What limit strategy we suggest?
> Limiting Metrics. Failures are often the result of too much pressure on the opti-
mization. By using metrics to set a standard or provide a limited incentive instead of a
presenting value to maximize, the overoptimization pressure can sometimes be mitigated
7. Abandoning Measurement. How we are going to review the model after applied on the field?
> Sometimes, the value of better incentivising partic-
ipants and the potential for perverse incentives issues make it worthwhile to be wary
of what Muller refers to as metric fixation.[Mul18] As he suggest, sometimes the best
solution is to do nothing - or at least nothing involving measurement.

**Comment by germonprez** [comment]
Closing as these issues are more corporately related and less about open source community health.

**Comment by germonprez** [comment]
Maybe create a blog post or a Discourse thread with respect to this issue.

**Comment by bhack** [comment]
In communities where we have an heavy presence of corporate members, developers and  repo gatekeepers it is going to impact a lot as all our metrics and our models are at risk to be deformed.
