### ISSUE TITLE
Outreachy: Conversion Rate Metric Model 

### ISSUE THREAD

**Issue by fernanda-ordonez** [chaoss/wg-metrics-models#18]
Hello everyone!
My name is Fernanda Ordoñez Jimenez, I'm an Outreachy applicant and here is my proposal on how I would deploy the conversion rate metric model: https://drive.google.com/file/d/1Qm8sBUaL5X1F7G7hmZVmOwr8nrSCGMcS/view?usp=sharing 

Best, 
Fernanda

**Comment by germonprez** [comment]
Thank you for posting this @fernanda-ordonez
