### ISSUE TITLE
Move Community Activity folders

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-metrics-models#27]
Hi @sgoggins and @eyehwan and @zhongjun2 

Could we move this material: 

https://github.com/chaoss/wg-metrics-models/tree/main/metrics-model-libs/community-activity

to be more precisely located in the implementations folder?

**Comment by eyehwan** [comment]
Hi @germonprez 

As we discussed on [slides](https://docs.google.com/presentation/d/1aZbUXfxmqYiDTyGYorMMlx-WADfZ8LyuGusjvuyob7s/edit#slide=id.g131d850e8db_5_1), we have agreed to move all the MMs under metric-model-libs folder.
Did I miss anything?

**Comment by germonprez** [comment]
Right! Thanks for this @eyehwan -- that the case, we need to move all MMs to the metric-model-libs folder. So these would need to be moved: 

https://github.com/chaoss/wg-metrics-models/tree/main/implementations

Correct?

**Comment by eyehwan** [comment]
Here is the structure of metric-model-libs folder:

```
metric-model-libs
└───Model A : including definition and implementations of this Model. 
│   |   definition: it contains the definition of MM, in the format of the MM template.
|   |   implementations: this folder include the implementations.
|   |   |   implementation A : Implementation in field A with real world data. 
|   |   |   |   algorithm
|   |   |   |   data-insight
|   |   |   |   data
|   |   |   implementation B : Implementation in field B with real world data. 
|   |   |   |   algorithm
|   |   |   |   data-insight
|   |   |   |   data
└───Model B
└───Model C
```
So yes, https://github.com/chaoss/wg-metrics-models/tree/main/implementations need to be moved under metric-model-libs.

**Comment by eyehwan** [comment]
I just add pr for it.

**Comment by germonprez** [comment]
Excellent! Merged!
