### ISSUE TITLE
Adding Metrics to the Metric Model Mindmap

### ISSUE THREAD

**Issue by xiaoya-yaya** [chaoss/wg-metrics-models#34]
The [metrics-model-libs/libs-mindmap](https://github.com/chaoss/wg-metrics-models/tree/main/metrics-model-libs/libs-mindmap) is a great starting point to navigate metrics.

From my perspective, mindmap enables related metrics to come into plain view. Thus, I suggest adding 
metrics that are included in each metric model.

**Comment by xiaoya-yaya** [comment]
[Markmap](https://markmap.js.org/) supports generating online mindmaps based on markdown files, and it also supports displaying hyperlinks, so it's another solution I'm suggesting. This could be an ongoing discussion.

**Comment by eyehwan** [comment]
@xiaoya-yaya I have add mindmap https://github.com/chaoss/chaoss.github.io/pull/3 to chaoss io page.

Similarly like https://eyehwan.github.io/wg-metrics-models/libs-mindmap/mindmap

**Comment by germonprez** [comment]
Is this done? If so, could the issue be closed?

**Comment by eyehwan** [comment]
Yes, I think we can close it.
