### ISSUE TITLE
Funding Markdown File for Improvements

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-metrics-models#39]
1. Consider https://chaoss.community/metric-job-opportunities/ as a metric with potential value
2. How and to what extent can we arrive at specific definitions of the types of sponsorship in a way that would be helpful? 
 - Corporate sponsorship (perhaps covered by other metrics)
 - Foundation sponsorship (perhaps too complex)
 - Upstream sponsorship (often funded by corporations for whom a project is essential upstream).

**Comment by emmairwin** [comment]
As per Slack request,  I think the definition of sponsorship is funding outside of formal structures like foundations, and grant programs, by individuals or companies with unreliable, or sem-unreliable consistancy of duration and amount.

For example I might start with 400 sponsorship, but with recession claw back to 20 (to keep my name listed as a sponsor but to respond to the reality of by budget), or I might start off as a regular sponsor, but stop at some point to sponsor another maintainer on another project.

**Comment by germonprez** [comment]
Closing as this is an issue that maybe was more appropriate for the Value WG (that no longer exists).
