### ISSUE TITLE
Remove Community Welcomingness

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-metrics-models#54]
Due to inactivity, I suggest that we remove the Community Welcomingness metrics model from the current library. 

It does not conform with the current format that we are using for our metrics models. 

I very much like the idea of a Community Welcomingness metrics model and I would hope to see it again in this WG once it is ready. 

The current components of the model are at: https://github.com/chaoss/wg-metrics-models/tree/main/metrics-model-libs/community-welcomingness/implementations

@sgoggins @ElizabethN @eyehwan

**Comment by ElizabethN** [comment]
We decided it could be included after all, and here's the PR #66. Going to close this. :+1:
