### ISSUE TITLE
Basic Project Health Metrics Model

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/wg-metrics-models#69]
In the last Common WG before the holidays, @germonprez suggested that I put together a new metrics model for basic project health measurements based on what I've been doing at VMware. Here's a first draft of the metrics model, and I'd love any feedback from the team!

https://docs.google.com/document/d/1jBBKIEYaeI61LKjYHTnCh3a4Ih7zq6LuZA_arBmr0_M/edit

Given that the metrics model WG meetings are after midnight my time, I'm not going to join a meeting to talk about it, but feel free to discuss it without me, and I can watch the video after the meeting :)

**Comment by ElizabethN** [comment]
This has been published [here](https://chaoss.community/kb/metrics-model-starter-project-health/)! Thanks for bringing this to fruition, @geekygirldawn! :rocket:
