### ISSUE TITLE
Metrics Models to be Released on Website

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/wg-metrics-models#70]
We have several models that have been developed and that are ready for release on the website:

1. [x] [Development Responsiveness](https://docs.google.com/document/d/13OF3QEQDjJX56lO9ew1V2sWrLwzjwfXg4SfoRARsuv8/edit)
2. [x] [CHAOSS DEI Event Badging](https://docs.google.com/document/d/1-MizYW38J1o8eJnQx3OK-8Qpoo-8o6qJcVvnvWCLCGg/edit) (as a model)
3. [x] [Community Activity](https://docs.google.com/document/d/1lrCjGXwDlrsx2b-xcelvCtIzAtPMPVs5qPq0mVBvXk4/edit)
4. [x] [Safety](https://docs.google.com/document/d/1sDycjgHutLHcyUyl1yIRtweDHvpKN9o0tANgp_kLN0Y/edit)
5. [x] [Community Service and Support](https://docs.google.com/document/d/1zVwq-D4gDuENzhzGeGd9pvOOS3RQI2MVF_mnAZW055c/edit)
6. [x] [Project Engagement](https://docs.google.com/document/d/1bQWMbvYv4CC-d-vHhptV7-t0HU4q4dkw4i6L6gpofDc/edit)
7. [x] [Funding](https://docs.google.com/document/d/1zMTYIZsMGzPIu37HPWdNWhGgzRyIy147fbSopHU-yS4/edit)
8. [x] [Project Awareness](https://docs.google.com/document/d/1i1rXCRso5pVbFkAYomaU3z0WQYqhPQ8-PrvLfiN7yWk/edit)

This issue is a placeholder for Elizabeth to add them for release.

**Comment by ElizabethN** [comment]
Also a note to self: Make sure to change the links to the metrics to our new Stable URL permalink.

**Comment by eyehwan** [comment]
Hi @ElizabethN ，I have created a PR to update Code quality guarantee's name #71 , would you please help review it? Thanks you. :)

BR/Yehui.

**Comment by ElizabethN** [comment]
Note to self: The only metrics models that are fully ready to be released: 
(We are missing some permalinks and some metrics still need to be developed for some of the above metrics)

- Funding
- DEI Event Badging

**Comment by germonprez** [comment]
What is missing from the others that are indicated as 'ready' on the spreadsheet?

**Comment by eyehwan** [comment]
Hi,

I think we can finalize it in the next model meeting next week..

BR//Yehui.

**Comment by ElizabethN** [comment]
Ok, I think we have all our metrics models released with the exception of Safety. This metric model looks very different than the rest of ours, so do we want to retro-fit it to our template for consistency? It might need a little work. 

Otherwise the metrics models can be found here: https://chaoss.community/kbtopic/all-metrics-models/

**Comment by ElizabethN** [comment]
[Safety](https://chaoss.community/kb/metrics-model-safety/) has now been published. Thanks for reworking this, @germonprez! :rocket:
